title: "Open prices"
author: "DeepMining Lab"
description: "Open-data initiative providing a standardized, continuously updated historical dataset of prices"
baseurl: "" 
url: "http://localhost:4000"

markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed

# syntax highlighting settings
kramdown: 
  hard_wrap: false
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
